#!/bin/bash

# update the package list and upgrade the installed packages
sudo apt-get update
sudo apt-get upgrade -y

# install necessary packages
sudo apt-get install -y python3 python3-pip python3-picamera python3-opencv git

# clone the github repo
#git clone https://github.com/rwlloyd/stupid-timelapse-videos.git

# create a directory for the timelapse photos
mkdir ~/timelapse

# create a Python script to capture the timelapse photos
cat > ~/stupid-timelapse-videos/save_img.py << EOF
#!/usr/bin/env python3
# Script to capture an image from a webcam and save it to a nominated directory
# Script intended to be fired by crontab on a linux system 
# Images saved in accordance with ISO8601 naming https://en.wikipedia.org/wiki/ISO_8601 ... sort of
# Crontab line generated by https://crontab-generator.org/

# Rob Lloyd. Lincoln 03/2023.

import argparse
import os
import cv2
import time
import logging

# Create an ArgumentParser object to handle command-line arguments
parser = argparse.ArgumentParser()
parser.add_argument('--name', required=True, default='newSequence', help='timelapse name')
parser.add_argument('--folder', default='/', help='path to save location')
parser.add_argument('--camera', type=int, default=0, help='frame rate of the output video')
args = parser.parse_args()

capture_name = args.name
folder_path = args.folder         
camera_num = args.camera

# Set up logging to a file
logging.basicConfig(filename=capture_name + '-logfile.log', level=logging.DEBUG)

if not os.path.exists(folder_path):     # Check if the folder path exists or not
    os.makedirs(folder_path)            # If the folder path does not exist, create the folder

camera = cv2.VideoCapture(camera_num)   # Initialize the camera capture object
time.sleep(3)                           # Wait for 3 seconds to allow the camera to initialize

try:
    ret, frame = camera.read()          # Read a frame from the camera
    if ret:                             # Check if the frame was read successfully
        current_time = time.strftime("%Y%m%d-%H%M%S")       # Get the current timestamp to use as the image filename
        file_name = f"{current_time}.jpg"                   # Create a unique filename for the image
        file_path = os.path.join(folder_path, file_name)    # Combine the folder path and filename to get the complete file path
        cv2.imwrite(file_path, frame)                       # Save the image to the specified folder
        logging.info('%s Image saved to %s', capture_name, file_name)
    else:
        logging.error('Failed to capture image from webcam')
except Exception as e:
    logging.error('An Error occurred: %s', e)

camera.release()                        # Release the camera capture object
cv2.destroyAllWindows()                 # Destroy CV2!
EOF

# make the Python script executable
chmod +x ~/timelapse/timelapse.py

# run the Python script
~/timelapse/timelapse.py

# write a new cronjob to the crontab file (this default fires every minute of the day)
echo "* * * * * python3 ~/stupid-timelapse-videos/save_img.py --name defaultTimelapse --folder /home/pi/defaultTimelapse --camera 0 >/dev/null 2>&1" >> /etc/crontab